version: '2'
services:
  bookingroot:
    image: bachelorproject/rabbitcluster:latest
    hostname: bookingroot
    restart: "unless-stopped"
    environment:
    - SERVICE=booking
    ports:
    - "15672:15672"
  customermanagementroot:
    image: bachelorproject/rabbitcluster:latest
    hostname: customermanagementroot
    restart: "unless-stopped"
    environment:
    - SERVICE=customermanagement
    ports:
    - "15673:15672"
  pricingroot:
    image: bachelorproject/rabbitcluster:latest
    hostname: pricingroot
    environment:
    - SERVICE=pricing
    restart: "unless-stopped"
    environment:
    - SERVICE=pricing
    ports:
    - "15674:15672"
  seatoverviewroot:
    image: bachelorproject/rabbitcluster:latest
    hostname: seatoverviewroot
    environment:
    - SERVICE=seatoverview
    restart: "unless-stopped"
    environment:
    - SERVICE=seatoverview
    ports:
    - "15675:15672"
  seatmanagementroot:
    image: bachelorproject/rabbitcluster:latest
    hostname: seatmanagementroot
    environment:
    - SERVICE=seatmanagement
    restart: "unless-stopped"
    ports:
    - "15676:15672"
networks:
  default:
    external:
       name: reservierung
